#!/bin/bash
#
# Copyright 2019,2023-2024 Gaël PORTAY
#
# SPDX-License-Identifier: LGPL-2.1-or-later
#

DOSH_DOCKER="podman" \
DOSH_DOCKER_RUN_EXTRA_OPTS="--userns keep-id --group-add keep-groups" \
exec dosh --no-auto-context "$@"
