#!/bin/sh
#
# Copyright (c) 2017 Gaël PORTAY <gael.portay@savoirfairelinux.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the MIT License.
#

set -e

# Create a container and remove it on exit
container="$(dsh --detach)"
trap 'docker rm -f $container' 0

# Run make and set docker shell as default shell
make SHELL="dsh --exec $container" "$@"
