FROM ubuntu:16.04

RUN groupadd --non-unique --gid @GID@ @USER@
RUN useradd  --non-unique --gid @GID@ --uid @UID@ --create-home --home-dir @HOME@ --shell /bin/sh @USER@
RUN groupadd --non-unique --gid @DID_GID@ dind
RUN usermod  --append --group dind @USER@
