= dosh(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: Docker Shell Manual
:man source: dosh 7

== NAME

dosh - run a user shell in a container with working directory bind mounted

== SYNOPSIS

Typical shell commands:

*dosh*    [(-|\+)abefhmnuvxC] [(-|+)o shopt] [SCRIPT_FILE  [ARGS...]]

*dosh* -c [(-|\+)abefhmnuvxC] [(-|+)o shopt] COMMAND [NAME [ARGS...]]

*dosh* -i [(-|\+)abefhmnuvxC] [(-|+)o shopt] [SCRIPT_FILE  [ARGS...]]

*dosh* -s [(-|\+)abefhmnuvxC] [(-|+)o shopt]               [ARGS...]

Advanced dosh container commands:

*dosh* --detach [OPTIONS]

*dosh* --exec CONTAINER [OPTIONS] [ARGS...]

*dosh* --attach CONTAINER [OPTIONS]

Advanced dosh image management commands:

*dosh* --tag

*dosh* --ls

*dosh* --gc [DOCKER_RMI_OPTIONS]

*dosh* --rmi [DOCKER_RMI_OPTIONS]

Extra docker front-end commands:

*dosh* --attach CONTAINER [DOCKER_ATTACH_OPTIONS]

*dosh* --kill   CONTAINER [DOCKER_KILL_OPTIONS]

*dosh* --rm     CONTAINER [DOCKER_RM_OPTIONS]

== DESCRIPTION

*dosh* is a sh-compatible front-end for *docker(1)* that executes commands read
from the standard input or from a file.

It runs a shell process in a new container with its own file system, the
current _working directory_ bind mounted, and the current _user/group_
privileges set.

When called without arguments, *dosh* defaults to running an interactive shell
as current _user_.

When a container shell is started, *dosh* reads and executes commands from
_~/.dosh_profile_, if that file exists. This may be inhibited by using the
option *--no-doshprofile*.

When a container shell is started, *dosh* reads and executes commands from
_./doshrc_, if that file exists. This may be inhibited by using the option
*--no-doshrc*.

*dosh* builds and runs images for another _platform_ if the option *--platform*
is set to a target different from the host platform. Official _platforms_ are
specified in the section *PLATFORMS*).

*dosh* has specific options to modify its behaviour; the option *--dockerfile*
specifies the path to the *Dockerfile(5)* to use; the option *--home* bind
mounts the user's home directory instead of _working directory_; the option
*--root* runs the container with the _root_ privileges. Other options are
specified in the section *OPTIONS*.

Under the hood, *dosh* builds and tags automatically a _docker image_ using the
*Dockerfile(5)* from the _current working directory_ through *docker-build(1)*.
It appends extra _RUN_ instructions to add the host _$USER/$GROUPS_ through
*groupadd(8)* and *useradd(8)* to the _docker image_. Once the image is built,
*dosh* runs the *$SHELL* entry-point with the given arguments specified via the
command-line through *docker-run(1)*.

== OPTIONS

*POSIX Shell related options*

**-c**::
	Read commands from command-line.

**-i**::
	Set interactive.

**-s**::
	Read commands from standard-input.

**-abefhmnuvxC** or **-o shopt**, **+abefhmnuvxC** or **+o shopt**::
	For a more thorough description of shopts, please refers to sh help.

*Bash specific options:*

**-klprtBDEHIPT** or **-O shopt**, **+klprtBDEHIPT** or **+O shopt**::
	For a more thorough description of shopts, please refers to bash help.

*Dash specific options:*

**-pqEIV**, **+pqEIV**::
	For a more thorough description of shopts, please refers to dash help.

**Zsh specific options:**

**-0123456789dgklprtwyBDEFGHIJKLMNOPQRSTUVWXYZ**, **+0123456789dgklprtwyBDEFGHIJKLMNOPQRSTUVWXYZ**::
	For a more thorough description of shopts, please refers to zsh help.

*Docker related options*

**--dockerfile FILE**::
	Path to the Dockerfile to use.

**--platform TARGET**::
	Set target platform.

**--context TAR**::
	Path to the context to send to docker daemon.

**--no-auto-context**::
	Disable automatic context sent to docker daemon.

**--no-extra-options**::
	Disable extra options given to docker commands.

**--no-doshprofile**::
	Disable read of ~/.dosh_profile.

**--no-doshrc**::
	Disable read of ./doshrc.

**--directory DIR**::
	Change to directory before doing anything else.

**--working-directory DIR**::
	Working directory inside the container.

**--sudo**::
	Run docker with sudo.

**--root**::
	Run as root.

**--dind**::
	Run dosh in dosh.

**--groups**::
	Run with host groups.

**--home**::
	Bind mount home directory.

**--mount-options OPTIONS**::
	Set bind mount volume options.
	For a more thorough description please refers to docker-run(1) manual.

**--shell SHELL**::
	Set shell interpretor.
	Equivalent to set DOSHELL=<SHELL>.

**--tag**::
	Print docker tag and exit.

**--ls**::
	List images and exit.

**--gc**::
	Cleanup unused images and exit.

**--build-only**::
	Build image if needed and exit.

**--build**::
	Build image.

**--rebuild**::
	Build image again, verbosely.
	Equivalent to --build --verbose.

**--rmi**::
	Remove image and exit.

**--detach**::
	Detach container.

**--exec CONTAINER**::
	Execute in container.

**--attach CONTAINER**::
	Attach container.

**--kill CONTAINER**::
	Kill container.

**--rm CONTAINER**::
	Remove container.

**--dry-run**::
	Do nothing; echo docker commands.

*Miscellaneous options*

**--verbose**::
	Turn on verbose mode.

**--version**::
	Print version.

**--help**::
	Print usage.

== ENVIRONMENT VARIABLES

**DOSHELL**::
	The full pathname to the shell to run in docker image.
	Equivalent to --shell <SHELL>.

**DOSHLVL**::
	Incremented by one each time an instance of dosh is started.

**DOSH_DOCKER**::
	The docker executable.

**DOSH_DOCKER_HOST**::
	The docker daemon socket to conect to.

**DOSH_DOCKERFILE**::
	The filename of the Dockerfile to use.
	Equivalent to --dockerfile <FILE>.

**DOSH_DOCKER_RUN_EXTRA_OPTS**::
	Set additionnal parameters to docker run command.

**DOSH_DOCKER_EXEC_EXTRA_OPTS**::
	Set additionnal parameters to docker exec command.

**DOSH_DOCKER_ATTACH_EXTRA_OPTS**::
	Set additionnal parameters to docker attach command.

**DOSH_DOCKER_KILL_EXTRA_OPTS**::
	Set additionnal parameters to docker kill command.

**DOSH_DOCKER_RM_EXTRA_OPTS**::
	Set additionnal parameters to docker rm command.

**DOSH_DOCKER_BUILD_EXTRA_OPTS**::
	Set additionnal parameters to docker build command.

**DOSH_DOCKER_RMI_EXTRA_OPTS**::
	Set additionnal parameters to docker rmi command.

== FILES

**~/.dosh_profile**::
	The personal initialization file.

**./.doshrc**::
	The local initialization file.

== PLATFORMS

**linux/amd64**::
	Intel/AMD x86 64-bit.

**linux/arm64**::
	ARMv8 64-bit.

**linux/arm/v6**::
	ARMv6 32-bit.

**linux/arm/v7**::
	ARMv7 32-bit.

== EXAMPLES

Run an _interactive shell_ in the latest _Ubuntu_ container

	$ echo FROM ubuntu >Dockerfile
	$ cat Dockerfile
	FROM ubuntu

	$ dosh
	sha256:777c682a9816
	gportay@4c3fb2d195d8:~$ 

Check for the _distribution_

	gportay@4c3fb2d195d8:~$ cat /etc/os-release
	DISTRIB_ID=Ubuntu
	DISTRIB_RELEASE=16.04
	DISTRIB_CODENAME=xenial
	DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
	NAME="Ubuntu"
	VERSION="16.04.1 LTS (Xenial Xerus)"
	ID=ubuntu
	ID_LIKE=debian
	PRETTY_NAME="Ubuntu 16.04.1 LTS"
	VERSION_ID="16.04"
	HOME_URL="http://www.ubuntu.com/"
	SUPPORT_URL="http://help.ubuntu.com/"
	BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
	VERSION_CODENAME=xenial
	UBUNTU_CODENAME=xenial

Check for _user_

	gportay@4c3fb2d195d8:~$ whoami
	gportay

Exit from container

	gportay@4c3fb2d195d8:~$ exit
	logout

Run the _commands_ above in the same container as a _shell_ script

	$ dosh "cat /etc/os-release && whoami"
	NAME="Ubuntu"
	VERSION="16.04.1 LTS (Xenial Xerus)"
	ID=ubuntu
	ID_LIKE=debian
	PRETTY_NAME="Ubuntu 16.04.1 LTS"
	VERSION_ID="16.04"
	HOME_URL="http://www.ubuntu.com/"
	SUPPORT_URL="http://help.ubuntu.com/"
	BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
	VERSION_CODENAME=xenial
	UBUNTU_CODENAME=xenial
	gportay
	logout

Check for _PWD_ bind mountage ; write the _distribution_ name to local file

	$ dosh -c "grep '^NAME=' /etc/os-release >os-release"

Read the contents outside the container

	$ cat os-release
	NAME="Ubuntu"

Specify the *Dockerfile(5)* to use

	$ dosh --dockerfile Dockerfile.fedora -c "grep '^NAME=' /etc/os-release"
	sha256:44d9de323a55
	NAME=Fedora

Change to another _directory_ before doing anything else

	$ cd /tmp
	$ dosh --directory "$OLDPWD" -c "grep '^NAME=' /etc/os-release"
	NAME="Ubuntu"
	$ cd -

Run shell as _root_ with _--root_ to perform privileged user operations into
container

	$ dosh --root
	root@4c3fb2d195d8:/# whoami
	root
	root@4c3fb2d195d8:/# apt-get install -y asciidoctor
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	asciidoctor is already the newest version (1.5.4-1).
	0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

Rebuild image if *Dockerfile(5)* has changed

	$ echo RUN apt-get update && apt-get install -y asciidoctor >>Dockerfile
	$ cat Dockerfile
	FROM ubuntu
	RUN apt-get update && apt-get install -y asciidoctor
	$ dosh --build
	sha256:777c682a9816
	gportay@31dd533203ea:~$ which asciidoctor
	/usr/bin/asciidoctor
	gportay@31dd533203ea:~$ exit
	logout

	$ dosh
	gportay@0406c4779648:~$ exit
	logout

Bind mount _$HOME_ directory

	$ echo $PWD
	/home/gportay/src/dosh
	$ echo $HOME
	/home/gportay

	$ dosh --home
	gportay@098ac1e92f20 ~/src/dosh $ echo $PWD
	/home/gportay/src/dosh
	gportay@098ac1e92f20 ~/src/dosh $ echo $HOME
	/home/gportay

Use _/bin/sh_ as default _$SHELL_

	$ echo $0
	bash

	$ dosh --shell /bin/sh
	$ echo $0
	/bin/sh

Detach container

	$ dosh --detach
	6b0e5f883ca5e176452bb234bccf70623a35b5d5f12ae56761a392a3e9f40125

	$ docker ps -a
	CONTAINER ID        IMAGE                                                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
	6b0e5f883ca5        dosh-dbc94874ef3f1be8f595c79fcaf36fd691dc2af3b7b29f291210cecc8f2beca2  "/bin/bash -c 'cd /ho"   7 seconds ago       Up 6 seconds                            determined_archimedes

Execute commands in it with _--exec_

	$ dosh --exec determined_archimedes -c 'hostname'
	6b0e5f883ca5

Attach to it using _--attach_

	$ dosh --attach determined_archimedes
	gportay@6b0e5f883ca5:~$ exit
	exit

Kill it using _--kill_

	$ dosh --kill determined_archimedes
	determined_archimedes

And do not forget to remove it using _--rm_

	$ dosh --rm determined_archimedes
	determined_archimedes

	$ docker ps -a
	CONTAINER ID        IMAGE                                                                  COMMAND                  CREATED             STATUS              PORTS               NAMES

== PATCHES

Submit patches at *https://github.com/gportay/dosh/pulls*

== BUGS

Report bugs at *https://github.com/gportay/dosh/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright 2017-2020,2023-2025 Gaël PORTAY

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 2.1 of the License, or (at your option) any
later version.

== SEE ALSO

docker-build(1), docker-run(1), groupadd(8), useradd(8)
