#!/bin/bash
#
# Copyright (c) 2017-2020 Gaël PORTAY
#
# SPDX-License-Identifier: MIT
#

# Called as program loader (shebang #!/usr/bin/dosh)
__="$_"
if [ "$__" != "/bin/bash" ] && [ "$__" = "$1" ]; then
	exec <"$1"
	shift
	set -- -s "$@"
	exec "$0" "$@"
elif [ "$__" != "/bin/bash" ] && [ "$__" = "$2" ]; then
	read -r -a args < <(echo "$1")
	shift
	exec <"$1"
	shift
	set -- "${args[@]}" -s "$@"
	exec "$0" "$@"
fi

set -e
set -u
set -o pipefail

VERSION="1.9"

usage() {
	cat <<EOF
Usage: ${0##*/}    [(-|+)abefhmnuvxC] [(-|+)o shopt] [SCRIPT_FILE  [ARGS...]]
       ${0##*/} -c [(-|+)abefhmnuvxC] [(-|+)o shopt] COMMAND [NAME [ARGS...]]
       ${0##*/} -s [(-|+)abefhmnuvxC] [(-|+)o shopt]               [ARGS...]

Run a shell as user in a container and bind mount cwd.

POSIX Shell related options:
      -c                        Read commands from command-line.
      -i                        Set interactive.
      -s                        Read commands from standard-input.
      -abefhmnuvxC or -o shopt,
      +abefhmnuvxC or +o shopt  For a more thorough description of shopts,
                                please refers to sh help.

Bash specific options:
      -klprtBDEHIPT or -O shopt,
      +klprtBDEHIPT or +O shopt For a more thorough description of shopts,
                                please refers to bash help.

Dash specific options:
      -pqEIV, +pqEIV            For a more thorough description of shopts,
                                please refers to dash help.

Zsh specific options:
      -0123456789dgklprtwyBDEFGHIJKLMNOPQRSTUVWXYZ,
      +0123456789dgklprtwyBDEFGHIJKLMNOPQRSTUVWXYZ
                                For a more thorough description of shopts,
                                please refers to zsh help.

Docker related options:
      --dockerfile FILE         Path to the Dockerfile to use.
      --context TAR             Path to the context to send to docker daemon.
      --no-auto-context         Disable automatic context sent to docker daemon.
      --no-extra-options        Disable extra options given to docker commands.
      --no-doshprofile          Disable read of ~/.dosh_profile
      --no-doshrc               Disable read of ./doshrc
      --directory DIR           Change to directory before doing anything else.
      --root                    Run as root.
      --dind                    Run dosh in dosh.
      --home                    Bind mount home directory.
      --shell SHELL             Set shell interpretor.
                                Equivalent to set DOSHELL=<SHELL>.
      --build                   Build image.
      --rebuild                 Build image again, verbosely.
                                Equivalent to --build --verbose.
      --rmi                     Remove image.
      --detach                  Detach container.
      --exec CONTAINER          Execute in container.
      --tag                     Print docker tag and exit.
      --dry-run                 Do nothing; echo docker commands.

Miscellaneous options:
      --verbose                 Turn on verbose mode.
      --version                 Print version.
      --help                    Print usage.

Environment variables:
      DOCKER                    The docker executable.

      DOSHELL                   The full pathname to the shell to run in docker
                                image.
                                Equivalent to --shell <SHELL>.

      DOSHLVL                   Incremented by one each time an instance of dosh
                                is started.

      DOSH_DOCKERFILE           The filename of the Dockerfile to use.
                                Equivalent to --dockerfile <FILE>.

      DOSH_DOCKER_RUN_EXTRA_OPTS
                                Set additionnal parameters to docker run
                                command.

      DOSH_DOCKER_EXEC_EXTRA_OPTS
                                Set additionnal parameters to docker exec
                                command.

      DOSH_DOCKER_BUILD_EXTRA_OPTS
                                Set additionnal parameters to docker build
                                command.

      DOSH_DOCKER_RMI_EXTRA_OPTS
                                Set additionnal parameters to docker rmi
                                command.
EOF
}

run() {
	if [[ ${dryrun:-} ]]; then
		[ "$1" != "exec" ] || shift
		echo "${@// /\\ }" >&2
		return
	fi

	"$@"
}

get_tag() {
	echo "dosh-$(realpath "$1" | sha256sum - | cut -d' ' -f1)"
}

docker_build() {
	local did
	local files
	local extraopts
	local context_file

	if [[ ${DOSH_NOBUILD:-} ]]; then
		return
	fi

	if [[ ! -e "$1" ]]; then
		echo "$1: No such Dockerfile"
		exit 1
	fi

	# Inject both user and group id.
	IFS=":" read -r -a did <<< "$(grep '^docker' /etc/group)"
	cat "$1" - <<EOF >doshfile

USER root
RUN grep -q "^$USER:" /etc/group \
 || groupadd --non-unique --gid ${GROUPS[0]} $USER \
 || addgroup -g ${GROUPS[0]} $USER
RUN grep -q "^$USER:" /etc/passwd \
 || useradd  --non-unique --gid ${GROUPS[0]} --uid $UID --create-home --home-dir $HOME --shell /bin/sh $USER \
 || adduser  -G $USER -u $UID -h $HOME -s /bin/sh -D $USER
RUN grep -q "^dind:" /etc/group \
 || groupadd --non-unique --gid ${did[2]} dind \
 || addgroup -g ${did[2]} dind
RUN grep -q "^dind:x:${did[2]}:.*$USER" /etc/group \
 || usermod  --append --group dind $USER \
 || addgroup $USER dind
RUN if test -d /etc/sudoers.d; then echo "%$USER ALL=(ALL) NOPASSWD: ALL" >"/etc/sudoers.d/$USER"; fi
EOF

	files=(doshfile)
	context_file="${3:-}"
	if ! [[ ${context_file:-} ]]; then
		while read -r -a words; do
			if ! [[ ${words[0]:-} ]]; then
				continue
			elif [[ ${words[0]^^} =~ ^(ADD|COPY)$ ]]; then
				# Remove keyword and destination path
				unset 'words[0]'
				unset 'words[-1]'

				for word in "${words[@]}"; do
					# Skip long option and sources with schema://
					if [[ $word =~ ^-- ]] ||
					   [[ $word =~ ^.*\:// ]]; then
						continue
					fi

					for f in $word; do
						files+=("$f")
					done
				done
				unset f
			elif [[ ${words[0]^^} =~ ^ENTRYPOINT$ ]]; then
				echo "Info: ENTRYPOINT is overridden by dosh"
			fi
		done <doshfile >&2
	fi

	# Append extra options if any
	read -r -a extraopts < <(echo "${DOSH_DOCKER_BUILD_EXTRA_OPTS:-}")
	if [ ${#extraopts[*]} -gt 0 ]; then
		buildopts+=("${extraopts[@]:-}")
	fi

	# Do not send build context to the daemon if neither ADD nor COPY instructions in Dockerfile.
	if [[ ${#files[@]} -gt 1 ]] && [[ ${no_auto_context:-} ]]; then
		echo "Info: ADD or COPY sends build context to daemon" >&2
		echo "      Consider option --context <TAR> to speed up the build of image." >&2
		echo "      First, generate the context archive as suggested by the command below:" >&2
		echo "          tar cf context.tar ${files[*]}" >&2
		echo "      Then, run dosh again and tell it to use the context archive:" >&2
		echo "          $0 --context context.tar ${BASH_ARGV[*]}" >&2
		run "${docker[@]}" build "${buildopts[@]}" --tag "$2" --file doshfile .
	else
		if ! [[ ${context_file:-} ]]; then
			run tar c "${files[@]}"
		else
			run tar rf "$context_file" "doshfile"
			run cat "$context_file"
		fi | \
		run "${docker[@]}" build "${buildopts[@]}" --tag "$2" --file doshfile -
	fi

	rm -f doshfile
}

docker_rmi() {
	local rmiopts
	local extraopts

	# Append extra options if any
	read -r -a extraopts < <(echo "${DOSH_DOCKER_RMI_EXTRA_OPTS:-}")
	if [ ${#extraopts[*]} -gt 0 ]; then
		rmiopts+=("${extraopts[@]:-}")
	fi

	run "${docker[@]}" rmi "${rmiopts[@]}" "$@"
}

is_doshopt() {
	if [[ "$1" =~ ^--(no-auto-context|no-extra-options|no-doshprofile|no-doshrc|root|dind|home|build|rebuild|rmi|detach)$ ]]; then
		return 0
	fi

	return 1
}

is_doshopt_argument() {
	if [[ "$1" =~ ^--(dockerfile|context|directory|shell|detach|exec)$ ]]; then
		return 0
	fi

	return 1
}

is_shopt() {
	# Do not handle -o shoptname here
	# sh (only)
	if [[ "$1" =~ ^[-+][abcefhimnsuvxC]$ ]]; then
		return 0
	fi

	# bash (specific)
	if [ "${DOSHELL##*/}" == "bash" ] &&
	   [[ "$1" =~ ^[-+][klprtBDEHIPT]$ ]]; then
		return 0
	fi

	# dash (specific)
	if [ "${DOSHELL##*/}" == "dash" ] &&
	   [[ "$1" =~ ^[-+][pqEIV]$ ]]; then
		return 0
	fi

	# zsh (specific)
	if [ "${DOSHELL##*/}" == "zsh" ] &&
	   [[ "$1" =~ ^[-+][0123456789dgklprtwyBDEFGHIJKLMNOPQRSTUVWXYZ]$ ]]; then
		return 0
	fi

	return 1
}

is_shopt_argument() {
	# sh (only)
	if [[ "$1" =~ ^[-+][o]$ ]]; then
		return 0
	fi

	# bash (specific)
	if [ "${DOSHELL##*/}" == "bash" ] &&
	   [[ "$1" =~ ^[-+]O$ ]]; then
		return 0
	fi

	return 1
}

shopts=()
read -r -a docker < <(echo "${DOCKER:-docker}")
dockerfile="${DOSH_DOCKERFILE:-Dockerfile}"
directory="."
opts=()
buildopts=("--quiet")
DOSHELL="${DOSHELL:-/bin/sh}"
DOSHLVL="${DOSHLVL:-0}"
while [ "$#" -ne 0 ]; do
	if [ "$1" = "--help" ]; then
		usage
		exit 0
	elif [ "$1" = "--version" ]; then
		echo "$VERSION"
		exit
	elif is_doshopt "$1"; then
		optname="${1//-/_}"
		optname="${optname:2}"
		eval "$optname=1"
	elif is_doshopt_argument "$1"; then
		optname="${1//-/_}"
		optname="${optname:2}"
		eval "$optname=\"$2\""
		shift
	elif [ "$1" = "--tag" ]; then
		get_tag "$directory/$dockerfile"
		exit
	elif [ "$1" = "--dry-run" ]; then
		dryrun=true
	elif [ "$1" = "--verbose" ]; then
		verbose=true
		buildopts=()
	elif is_shopt "$1"; then
		shopts+=("$1")
		eval "opt_${1:1:1}=1"
	elif is_shopt_argument "$1"; then
		shopts+=("$1")
		eval "opt_${1:1:1}=\"${2:-1}\""
		if [ $# -gt 1 ]; then
			shopts+=("$2")
			shift
		fi
	elif [ "$1" = "--" ]; then
		shift
		break
	else
		break
	fi
	shift
done

# Apply dosh options to dosh environment variables
# --shell SHELL to DOSHELL
if [[ ${shell:-} ]]; then
	DOSHELL="$shell"
fi
# --dockerfile FILE to DOSH_DOCKERFILE
if [[ ${dockerfile:-} ]]; then
	DOSH_DOCKERFILE="$dockerfile"
fi
# --no-extra-options resets DOSH_DOCKER_*_EXTRA_OPTS
if [[ ${no_extra_options:-} ]]; then
	DOSH_DOCKER_RUN_EXTRA_OPTS=
	DOSH_DOCKER_EXEC_EXTRA_OPTS=
	DOSH_DOCKER_BUILD_EXTRA_OPTS=
	DOSH_DOCKER_RMI_EXTRA_OPTS=
fi

# Change directory
cd "$directory"

# Source profile files
if [[ ! ${no_doshprofile:-} ]] && [ -e ~/.dosh_profile ]; then
	. ~/.dosh_profile
fi
if [[ ! ${no_doshrc:-} ]] && [ -e ./doshrc ]; then
	. ./doshrc
fi

# Remove image and exit
if [[ ${rmi:-} ]]; then
	# Remove image if exist
	tag="$(get_tag "$DOSH_DOCKERFILE")"
	docker_rmi "$tag" "$@" >&2
	exit
fi

# Run in a new container
if ! [[ ${exec:-} ]]; then
	# Rebuild or automatically build image if it does not exist
	tag="$(get_tag "$DOSH_DOCKERFILE")"
	imageid="$("${docker[@]}" images -q "$tag")"
	if [[ ${build:-} ]] || [[ ${rebuild:-} ]] || ! [[ ${imageid:-} ]]; then
		# Reset quiet option when image does not exist or rebuild or if verbose option is set
		if ! [[ ${imageid:-} ]] || [[ ${rebuild:-} ]] || [[ ${verbose:-} ]]; then
			buildopts=()
		fi
		# Remove previous image
		if [[ ${imageid:-} ]]; then
			docker_rmi "$tag" >&2
		fi
		docker_build "$DOSH_DOCKERFILE" "$tag" "${context:-}" >&2
	fi

	# Detach container
	if [[ ${detach:-} ]]; then
		opts+=("--detach")
	# Remove the container at exit
	else
		opts+=("--rm")
	fi

	# Bind mount home
	if [[ ${home:-} ]]; then
		opts+=("--volume" "$HOME:/home/$USER")
	# Bind mount current working directory
	else
		opts+=("--volume" "$PWD:$PWD")
	fi
fi

# Set current user privileges for dosh-in-dosh
if [[ ${dind:-} ]]; then
	opts+=("--user" "$UID:dind")
	opts+=("--volume" "/var/run/docker.sock:/var/run/docker.sock")
	opts+=("--volume" "$0:/bin/dosh:ro")
# Set current user privileges
elif ! [[ ${root:-} ]]; then
	opts+=("--user" "$UID:${GROUPS[0]}")
fi

# Set interactive
if [[ ${opt_i:-} ]] || [[ ${opt_s:-} ]] || [ "$#" -eq 0 ]; then
	opts+=("--interactive")

	# Allocate a pseudo-TTY if stdin/stderr are TTY
	if [ -t 0 ] && [ -t 2 ]; then
		opts+=("--tty")
	fi
fi

# Change to present working directory
opts+=("--workdir" "$PWD")

# Prepend shell options if any
if [ ${#shopts[*]} -gt 0 ]; then
	set -- "${shopts[@]:-}" "$@"
fi

# Execute in existing container
if [[ ${exec:-} ]]; then
	run exec "${docker[@]}" exec "${opts[@]}" ${DOSH_DOCKER_EXEC_EXTRA_OPTS:-} "$exec" "$DOSHELL" "$@"
# Run in a new container
else
	opts+=("--env" "DOSHLVL=$((DOSHLVL+1))")
	opts+=("--entrypoint" "$DOSHELL")
	if [[ ${verbose:-} ]]; then
		echo "$tag"
	fi >&2
	run exec "${docker[@]}" run "${opts[@]}" ${DOSH_DOCKER_RUN_EXTRA_OPTS:-} "$tag" "$@"
fi
