= dsh(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@savoirfairelinux.com
:lang: en
:man manual: docker-scripts Manual
:man source: dsh 1.0

== NAME

dsh - run a user shell in a container with pwd bind mounted

== SYNOPSIS

*dsh* [OPTIONS] [COMMAND] [ARG...]

== DESCRIPTION

Runs the _command_ process in a new container; using the current _user_, with
_pwd_ bind mounted.

When called without arguments, *dsh* defaults to running an interactive shell
as current _user_.

Under the hood, *dsh* builds its _docker image_ using the *Dockerfile(5)* from
the _current working directory_ inside *docker-build(1)*.  *dsh* appends a
*groupadd(8)* and a *useradd(8)* _RUN_ commands to it, to add the
_$USER/$GROUPS_ to the container. Once the image is build, the _command_ is run
into *$SHELL -c* using user _$USER_ through *docker-run*.

== OPTIONS

**-c**
	Read commands from command-line.

**-i**
	Set interactive.

**-s**
	Read commands from standard-input.

**-F or --dockerfile FILE**
	Path to the Dockerfile to use.

**-C or --directory DIR**
	Change to directory before doing anything else.

**--root**
	Run as root.

**--home**
	Bind mount home directory.

**--sh**
	Set /bin/sh as default shell.
	Equivalent to set SHELL=/bin/sh.

**--build**
	Build image.

**--detach**
	Detach container.

**--exec CONTAINER**
	Execute in container.

**-N or --no-do**
	Do nothing; echo docker commands.

**-v or --verbose**
	Turn on verbose mode.

**-h or --help**
	Print usage.

== EXAMPLES

Run an _interactive shell_ in the latest _Ubuntu_ container

	$ echo FROM ubuntu >Dockerfile
	$ cat Dockerfile
	FROM ubuntu

	$ dsh
	sha256:777c682a9816
	gportay@4c3fb2d195d8:~$ 

Check for the _distribution_

	gportay@4c3fb2d195d8:~$ cat /etc/os-release
	DISTRIB_ID=Ubuntu
	DISTRIB_RELEASE=16.04
	DISTRIB_CODENAME=xenial
	DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
	NAME="Ubuntu"
	VERSION="16.04.1 LTS (Xenial Xerus)"
	ID=ubuntu
	ID_LIKE=debian
	PRETTY_NAME="Ubuntu 16.04.1 LTS"
	VERSION_ID="16.04"
	HOME_URL="http://www.ubuntu.com/"
	SUPPORT_URL="http://help.ubuntu.com/"
	BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
	VERSION_CODENAME=xenial
	UBUNTU_CODENAME=xenial

Check for _user_

	gportay@4c3fb2d195d8:~$ whoami
	gportay

Exit from container

	gportay@4c3fb2d195d8:~$ exit
	logout

Run the _commands_ above in the same container as a _shell_ script

	$ dsh "cat /etc/os-release && whoami"
	NAME="Ubuntu"
	VERSION="16.04.1 LTS (Xenial Xerus)"
	ID=ubuntu
	ID_LIKE=debian
	PRETTY_NAME="Ubuntu 16.04.1 LTS"
	VERSION_ID="16.04"
	HOME_URL="http://www.ubuntu.com/"
	SUPPORT_URL="http://help.ubuntu.com/"
	BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
	VERSION_CODENAME=xenial
	UBUNTU_CODENAME=xenial
	gportay
	logout

Check for _PWD_ bind mountage ; write the _distribution_ name to local file

	$ dsh -c "grep '^NAME=' /etc/os-release >os-release"

Read the contents outside the container

	$ cat os-release
	NAME="Ubuntu"

Specify the *Dockerfile(5)* to use

	$ dsh -F Dockerfile.fedora -c "grep '^NAME=' /etc/os-release"
	sha256:44d9de323a55
	NAME=Fedora

Change to another _directory_ before doing anything else

	$ cd /tmp
	$ dsh -C "$OLDPWD" -c "grep '^NAME=' /etc/os-release"
	NAME="Ubuntu"
	$ cd -

Run shell as _root_ with _--root_ to perform privileged user operations into
container

	$ dsh --root
	root@4c3fb2d195d8:/# whoami
	root
	root@4c3fb2d195d8:/# apt-get install -y asciidoctor
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	asciidoctor is already the newest version (1.5.4-1).
	0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

Rebuild image if *Dockerfile(5)* has changed

	$ echo RUN apt-get update && apt-get install -y asciidoctor >>Dockerfile
	$ cat Dockerfile
	FROM ubuntu
	RUN apt-get update && apt-get install -y asciidoctor
	$ dsh --build
	sha256:777c682a9816
	gportay@31dd533203ea:~$ which asciidoctor
	/usr/bin/asciidoctor
	gportay@31dd533203ea:~$ exit
	logout

	$ dsh
	gportay@0406c4779648:~$ exit
	logout

Bind mount _$HOME_ directory

	$ echo $PWD
	/home/gportay/src/docker-scripts
	$ echo $HOME
	/home/gportay

	$ dsh --home
	gportay@098ac1e92f20 ~/src/docker-scripts $ echo $PWD
	/home/gportay/src/docker-scripts
	gportay@098ac1e92f20 ~/src/docker-scripts $ echo $HOME
	/home/gportay

Use _/bin/sh_ as default _$SHELL_

	$ echo $0
	bash

	$ dsh --sh
	$ echo $0
	/bin/sh

Detach container

	$ dsh --detach
	6b0e5f883ca5e176452bb234bccf70623a35b5d5f12ae56761a392a3e9f40125

	$ docker ps -a
CONTAINER ID        IMAGE                                                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
6b0e5f883ca5        dsh-dbc94874ef3f1be8f595c79fcaf36fd691dc2af3b7b29f291210cecc8f2beca2   "/bin/bash -c 'cd /ho"   7 seconds ago       Up 6 seconds                            determined_archimedes

Execute commands in it with _--exec_

	dsh --exec 6b0e5f883ca5e176452bb234bccf70623a35b5d5f12ae56761a392a3e9f40125 -c 'hostname'
	6b0e5f883ca5

Attach to it using *docker-attach(1)*

	$ docker attach 6b0e5f883ca5e176452bb234bccf70623a35b5d5f12ae56761a392a3e9f40125
	gportay@6b0e5f883ca5:~$ exit
	exit

Stop it using *docker-stop(1)*

	$ docker stop 6b0e5f883ca5
	6b0e5f883ca5e176452bb234bccf70623a35b5d5f12ae56761a392a3e9f40125

And do not forget to remove it using *docker-rm(1)*

	$ docker rm 6b0e5f883ca5
	6b0e5f883ca5e176452bb234bccf70623a35b5d5f12ae56761a392a3e9f40125

	$ docker ps -a
CONTAINER ID        IMAGE                                                                  COMMAND                  CREATED             STATUS              PORTS               NAMES

== BUGS

Report bugs at *https://github.com/gazoo74/docker-scripts/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@savoirfairelinux.com*

== COPYRIGHT

Copyright (c) 2017 Gaël PORTAY

This program is free software: you can redistribute it and/or modify it under
the terms of the MIT License.

== SEE ALSO

docker-build(1), docker-run(1), groupadd(8), useradd(8)
