#!/bin/sh
#
# Copyright (c) 2017-2018 Gaël PORTAY <gael.portay@savoirfairelinux.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the MIT License.
#

exec dosh --dockerfile Dockerfile.zsh --shell /bin/zsh "$@"
